let bank=[],test=[],answers=[],current=0,remaining=0,timer=null;const app=document.getElementById('app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function home(){const subjects=await fetch('subjects.json').then(r=>r.json());app.innerHTML=`<div class="wrap"><div class="card start"><h1>ECET MCQ Test</h1><p>All questions • 1 minute per question + 20 minutes</p>${subjects.map(s=>`<button onclick="loadSubject('${s.file}')">${esc(s.name)}</button>`).join(' ')}</div></div>`}
async function loadSubject(file){bank=await fetch(file).then(r=>r.json());if(!bank.length){app.innerHTML='<div class="wrap"><div class="card"><h2>No questions found</h2></div></div>';return}start()}
function start(){clearInterval(timer);test=[...bank];answers=Array(test.length).fill(null);current=0;remaining=test.length*60+20*60;timer=setInterval(()=>{remaining--;updateTimer();if(remaining<=0){remaining=0;submit()}},1000);render()}
function updateTimer(){const e=document.getElementById('timer');if(!e)return;const m=Math.floor(remaining/60),s=remaining%60;e.textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
function choose(v){answers[current]=v;render()}function go(n){current=Math.max(0,Math.min(test.length-1,n));render()}
function render(){const q=test[current];const hasOptions=Array.isArray(q.options)&&q.options.length===4;app.innerHTML=`<div class="top"><h1>ECET Digital Electronics</h1><div class="timer" id="timer"></div></div><div class="wrap"><div class="card"><div class="meta">Question ${current+1} of ${test.length} • ${q.year} ${q.state} • PYQ ${q.questionNumber}</div>${hasOptions?'':`<div class="notice">This question's option text was not cleanly recovered by OCR. Please verify it before using this question in a scored test.</div>`}<div class="question">${esc(q.question)}</div>${hasOptions?q.options.map((o,k)=>`<label class="option"><input type="radio" name="answer" ${answers[current]===k?'checked':''} onchange="choose(${k})"><b>${'ABCD'[k]}.</b> ${esc(o)}</label>`).join(''):'<div class="notice">Options unavailable in the OCR data.</div>'}<div class="palette">${test.map((_,k)=>`<button class="num ${answers[k]!==null?'answered':''} ${k===current?'current':''}" onclick="go(${k})">${k+1}</button>`).join('')}</div><div class="buttons"><button onclick="go(current-1)" ${current===0?'disabled':''}>Previous</button><button onclick="go(current+1)" ${current===test.length-1?'disabled':''}>Next</button><button class="submit" onclick="submit()">Submit Test</button></div></div></div>`;updateTimer()}
function submit(){clearInterval(timer);const answered=answers.filter(v=>v!==null).length,unanswered=test.length-answered,scorable=test.filter(q=>Number.isInteger(q.answer));const canScore=scorable.length===test.length;const score=canScore?test.reduce((s,q,n)=>s+(answers[n]===q.answer?1:0),0):null;app.innerHTML=`<div class="wrap"><div class="card"><h1>Test Completed</h1><div class="stats"><div class="stat"><b>${score===null?'—':score}</b>Score / ${test.length}</div><div class="stat"><b>${answered}</b>Answered</div><div class="stat"><b>${unanswered}</b>Unanswered</div></div>${canScore?'':'<p class="muted">The current OCR question bank does not contain a verified answer key, so the score is not guessed.</p>'}<br><button onclick="start()">Retry Test</button><h2>Review</h2>${test.map((q,n)=>`<div class="review"><b>Q${n+1}</b> • ${q.year} ${q.state}<br>${esc(q.question)}<br>Your answer: ${answers[n]===null?'Unanswered':'ABCD'[answers[n]]}${Number.isInteger(q.answer)?' • Correct: '+('ABCD'[q.answer]):''}</div>`).join('')}</div></div>`}
home();