let bank=[],test=[],answers=[],i=0,left=3600,timer=null;const app=document.getElementById("app"),TOTAL=50;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function home(){const ss=await fetch("subjects.json").then(r=>r.json());app.innerHTML=`<div class="card start"><h1>ECET MCQ Test</h1><p>50 questions • 60 minutes</p>${ss.map(s=>`<button onclick="load('${s.file}')">${esc(s.name)}</button>`).join(" ")}</div>`}
async function load(f){bank=await fetch(f).then(r=>r.json());if(bank.length<50){app.innerHTML=`<div class="card"><h2>Question bank not ready</h2><p>Add at least 50 questions to this subject JSON file.</p></div>`;return}start()}
function start(){test=[...bank].sort(()=>Math.random()-.5).slice(0,50);answers=Array(50).fill(null);i=0;left=3600;clearInterval(timer);timer=setInterval(()=>{left--;clock();if(left<=0){left=0;submit()}},1000);render()}
function clock(){const e=document.querySelector(".timer");if(e)e.textContent=String(Math.floor(left/60)).padStart(2,"0")+":"+String(left%60).padStart(2,"0")}
function pick(v){answers[i]=v;render()}function go(n){i=Math.max(0,Math.min(49,n));render()}
function render(){const q=test[i];app.innerHTML=`<div class="top"><h1>ECET Digital Electronics</h1><div class="timer"></div></div><div class="card"><div class="meta">Question ${i+1} of 50 • ${q.year||""} ${q.state||""}</div><div class="question">${esc(q.question)}</div>${q.options.map((o,k)=>`<label class="opt"><input type="radio" name="a" ${answers[i]===k?"checked":""} onchange="pick(${k})"><b>${"ABCD"[k]}.</b> ${esc(o)}</label>`).join("")}<div class="palette">${test.map((_,k)=>`<button class="num ${answers[k]!==null?"answered":""} ${k===i?"current":""}" onclick="go(${k})">${k+1}</button>`).join("")}</div><div class="buttons"><button onclick="go(i-1)" ${i===0?"disabled":""}>Previous</button><button onclick="go(i+1)" ${i===49?"disabled":""}>Next</button><button class="submit" onclick="submit()">Submit</button></div></div>`;clock()}
function submit(){clearInterval(timer);const answered=answers.filter(x=>x!==null).length,un=50-answered,has=test.some(q=>Number.isInteger(q.answer));let score=has?test.reduce((s,q,n)=>s+(Number.isInteger(q.answer)&&answers[n]===q.answer?1:0),0):null;app.innerHTML=`<div class="card"><h1>Result</h1><div class="stats"><div class="stat"><b>${score===null?"—":score}</b>Score / 50</div><div class="stat"><b>${answered}</b>Answered</div><div class="stat"><b>${un}</b>Unanswered</div></div>${has?"":"<p>Add verified answer values (0=A, 1=B, 2=C, 3=D) to enable scoring.</p>"}<br><button onclick="start()">Retry Test</button><h2>Review</h2>${test.map((q,n)=>`<div style="padding:12px 0;border-top:1px solid #ddd"><b>Q${n+1}</b><br>${esc(q.question)}<br>Your answer: ${answers[n]===null?"Unanswered":"ABCD"[answers[n]]}${Number.isInteger(q.answer)?` • Correct: ${"ABCD"[q.answer]}`:""}</div>`).join("")}</div>`}
home();