let bank=[],test=[],answers=[],i=0,left=0,timer=null;const app=document.getElementById('app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function home(){const ss=await fetch('subjects.json').then(r=>r.json());app.innerHTML=`<div class="card start"><h1>ECET MCQ Test</h1><p>Digital Electronics • All questions • 1 minute/question + 20 minutes</p>${ss.map(s=>`<button onclick="loadSubject('${s.file}')">${esc(s.name)}</button>`).join(' ')}</div>`}
async function loadSubject(f){bank=await fetch(f).then(r=>r.json());if(!bank.length){app.innerHTML='<div class="card"><h2>No questions found</h2></div>';return}start()}
function start(){test=[...bank];answers=Array(test.length).fill(null);i=0;left=test.length*60+1200;clearInterval(timer);timer=setInterval(()=>{left--;clock();if(left<=0){left=0;submit()}},1000);render()}
function clock(){const e=document.querySelector('.timer');if(e)e.textContent=String(Math.floor(left/60)).padStart(2,'0')+':'+String(left%60).padStart(2,'0')}
function pick(v){answers[i]=v;render()}function go(n){i=Math.max(0,Math.min(test.length-1,n));render()}
function render(){const q=test[i];const hasText=q.options&&q.options.length===4;app.innerHTML=`<div class="top"><h1>ECET Digital Electronics</h1><div class="timer"></div></div><div class="card"><div class="meta">Question ${i+1} of ${test.length} • ${q.year} ${q.state} • PYQ ${q.pyqQuestion}</div><div class="question">${esc(q.question)}</div><div class="hint">Original scanned question-paper image — use this image for the exact question, symbols and options.</div><img class="source" src="${esc(q.image)}" alt="Original ECET question paper page"><div>${hasText?q.options.map((o,k)=>`<label class="opt"><input type="radio" name="a" ${answers[i]===k?'checked':''} onchange="pick(${k})"><b>${'ABCD'[k]}.</b> ${esc(o)}</label>`).join(''):`<label class="opt"><input type="radio" name="a" ${answers[i]===0?'checked':''} onchange="pick(0)"><b>A.</b> Select option A from the image</label><label class="opt"><input type="radio" name="a" ${answers[i]===1?'checked':''} onchange="pick(1)"><b>B.</b> Select option B from the image</label><label class="opt"><input type="radio" name="a" ${answers[i]===2?'checked':''} onchange="pick(2)"><b>C.</b> Select option C from the image</label><label class="opt"><input type="radio" name="a" ${answers[i]===3?'checked':''} onchange="pick(3)"><b>D.</b> Select option D from the image</label>`}</div><div class="palette">${test.map((_,k)=>`<button class="num ${answers[k]!==null?'answered':''} ${k===i?'current':''}" onclick="go(${k})">${k+1}</button>`).join('')}</div><div class="buttons"><button onclick="go(i-1)" ${i===0?'disabled':''}>Previous</button><button onclick="go(i+1)" ${i===test.length-1?'disabled':''}>Next</button><button class="submit" onclick="submit()">Submit</button></div></div>`;clock()}
function submit(){clearInterval(timer);const answered=answers.filter(x=>x!==null).length,un=test.length-answered;app.innerHTML=`<div class="card"><h1>Test Completed</h1><div class="stats"><div class="stat"><b>${answered}</b>Answered</div><div class="stat"><b>${un}</b>Unanswered</div><div class="stat"><b>${test.length}</b>Total</div></div><p>The question bank is source-backed, but verified answer keys have not been added yet. I will add those separately rather than guessing.</p><button onclick="start()">Retry Test</button><h2>Review</h2>${test.map((q,n)=>`<div class="review"><b>Q${n+1}</b> • ${q.year} ${q.state} • PYQ ${q.pyqQuestion}<br>${esc(q.question)}<br>Your answer: ${answers[n]===null?'Unanswered':'ABCD'[answers[n]]}</div>`).join('')}</div>`}
home();
