/* ECET Online Test backend — Google Apps Script */
const SPREADSHEET_ID='1QDu7YTv-MWm9jRuVsmRBGjwuBD6WFtj_4bRqj5B8hds';
const SITE_URL='https://example.com/'; // Optional fallback; client sends direct URLs.
const SHEETS={
 Users:['Timestamp','Name','Email','LastSubject','LastTestUrl'],
 Results:['ResultId','Timestamp','Name','Email','Subject','SubjectId','Score','Total','Percentage','Correct','Wrong','Unanswered','TotalTimeSec','StartTime','EndTime','Rank','RankOutOf','RevisionAvailableAt','RevisionUnlockedEmailSent','TestUrl'],
 Answers:['ResultId','Email','Subject','QuestionId','Year','State','QuestionNumber','SelectedIndex','CorrectIndex','IsCorrect','TimeSpentSec','MarkedForReview'],
 WrongAnswers:['WrongId','ResultId','Email','Subject','QuestionId','Year','State','QuestionNumber','Question','OptionsJSON','CorrectIndex','SelectedIndex','MistakeType','DateAdded','RevisionDueDate','Revised','ReminderSent','TestUrl'],
 Rankings:['Subject','Email','Name','BestPercentage','BestScore','Total','Attempts','LastAttempt'],
 RevisionHistory:['Email','Subject','QuestionId','ActionDate','Action','MistakeType'],
 EmailQueue:['QueueId','ToEmail','EmailType','Subject','HtmlBody','CreatedAt','SentAt','Status'],
 SubmittedSessions:['ExamSessionId','ResultId','Email','Subject','SubmittedAt'],
 Reminders:['ReminderId','Email','UserName','Name','Message','RelatedTask','RelatedUrl','Frequency','NextRunAt','Status','Enabled','CreatedAt','UpdatedAt','LastSentAt'],
 Notifications:['NotificationId','ReminderId','Email','UserName','Name','Message','RelatedTask','RelatedUrl','ScheduledAt','SentAt','Status','Error','RetryCount']
};
function ss_(){return SpreadsheetApp.openById(SPREADSHEET_ID)}
function sh_(n){return ss_().getSheetByName(n)}
function tz_(){return Session.getScriptTimeZone()||'Asia/Kolkata'}
function iso_(d){return Utilities.formatDate(new Date(d),tz_(),"yyyy-MM-dd'T'HH:mm:ssXXX")}
function display_(d){return Utilities.formatDate(new Date(d),tz_(),'dd MMM yyyy, hh:mm a')}
function email_(v){return String(v||'').trim().toLowerCase()}
function esc_(s){return String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function out_(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
function bool_(v){return v===true||String(v).toLowerCase()==='true'||String(v)==='1'}
function ensureSheets_(){const book=ss_();Object.keys(SHEETS).forEach(n=>{let s=book.getSheetByName(n);if(!s)s=book.insertSheet(n);const want=SHEETS[n];if(s.getLastRow()===0){s.getRange(1,1,1,want.length).setValues([want]).setFontWeight('bold');s.setFrozenRows(1)}else{const h=s.getRange(1,1,1,Math.max(1,s.getLastColumn())).getValues()[0].map(String);const miss=want.filter(x=>!h.includes(x));if(miss.length)s.getRange(1,s.getLastColumn()+1,1,miss.length).setValues([miss]).setFontWeight('bold')}});const d=book.getSheetByName('Sheet1');if(d&&d.getLastRow()===0&&book.getSheets().length>1)book.deleteSheet(d)}
function objs_(s){if(!s||s.getLastRow()<2)return[];const v=s.getDataRange().getValues(),h=v[0];return v.slice(1).filter(r=>r.join('')!=='').map(r=>{const o={};h.forEach((x,i)=>o[x]=r[i]);return o})}
function append_(s,headers,o){s.appendRow(headers.map(h=>o[h]!==undefined?o[h]:''))}
function appendMany_(s,headers,arr){if(!arr.length)return;s.getRange(s.getLastRow()+1,1,arr.length,headers.length).setValues(arr.map(o=>headers.map(h=>o[h]!==undefined?o[h]:'')))}
function doGet(e){try{ensureSheets_();const a=String(e.parameter.action||'');if(a==='ping')return out_({ok:true,time:iso_(new Date())});if(a==='dashboard')return out_({ok:true,data:dashboard_(e.parameter.email)});if(a==='mistakes')return out_({ok:true,data:mistakes_(e.parameter.email)});if(a==='history')return out_({ok:true,data:history_(e.parameter.email)});if(a==='reminders')return out_({ok:true,data:reminders_(e.parameter.email)});if(a==='notifications')return out_({ok:true,data:notifications_(e.parameter.email)});return out_({ok:false,error:'Unknown action'})}catch(err){return out_({ok:false,error:String(err)})}}
function doPost(e){try{ensureSheets_();const b=JSON.parse(e.postData?.contents||'{}'),a=b.action;if(a==='register')return out_(register_(b));if(a==='submitExam')return out_(submitExam_(b));if(a==='submitRevision')return out_(submitRevision_(b));if(a==='createReminder')return out_(createReminder_(b));if(a==='updateReminder')return out_(updateReminder_(b));if(a==='toggleReminder')return out_(toggleReminder_(b));if(a==='deleteReminder')return out_(deleteReminder_(b));if(a==='retryNotification')return out_(retryNotification_(b));return out_({ok:false,error:'Unknown action'})}catch(err){return out_({ok:false,error:String(err)})}}
function register_(b){const e=email_(b.email);if(!e)return{ok:false,error:'Email is required'};append_(sh_('Users'),SHEETS.Users,{Timestamp:new Date(),Name:b.name,Email:e,LastSubject:b.subject||'',LastTestUrl:b.testUrl||''});return{ok:true}}
function practiceRank_(subject,e,p){const rows=objs_(sh_('Results')).filter(r=>String(r.Subject)===String(subject)),best={};rows.forEach(r=>{const em=email_(r.Email);if(!em)return;const pct=Number(r.Percentage)||0;if(best[em]===undefined||pct>best[em])best[em]=pct});const me=email_(e),cur=Number(p)||0;if(best[me]===undefined||cur>best[me])best[me]=cur;const rank=1+Object.values(best).filter(x=>x>cur).length;return{rank,total:Object.keys(best).length}}
function submitExam_(b){const sid=String(b.examSessionId||'').trim();if(sid){const prior=objs_(sh_('SubmittedSessions')).find(x=>String(x.ExamSessionId)===sid);if(prior){const old=objs_(sh_('Results')).find(x=>String(x.ResultId)===String(prior.ResultId));return resultResponse_(old,true)}}
  const now=new Date(),start=new Date(b.startTime||now),e=email_(b.email),pct=Math.max(0,Math.min(100,Number(b.percentage)||0)),rank=practiceRank_(b.subject,e,pct),id=Utilities.getUuid(),unlock=new Date(now.getTime()+24*60*60*1000);
  append_(sh_('Results'),SHEETS.Results,{ResultId:id,Timestamp:now,Name:b.name,Email:e,Subject:b.subject,SubjectId:b.subjectId,Score:Number(b.score)||0,Total:Number(b.total)||0,Percentage:pct,Correct:Number(b.correct)||0,Wrong:Number(b.wrong)||0,Unanswered:Number(b.unanswered)||0,TotalTimeSec:Number(b.totalTime)||0,StartTime:start,EndTime:now,Rank:rank.rank,RankOutOf:rank.total,RevisionAvailableAt:unlock,RevisionUnlockedEmailSent:false,TestUrl:b.testUrl||''});
  const due=unlock,ans=[],mist=[];(b.detail||[]).forEach(d=>{const answered=d.selected!==null&&d.selected!==undefined&&d.selected!=='';const correct=answered&&Number(d.selected)===Number(d.correct);ans.push({ResultId:id,Email:e,Subject:b.subject,QuestionId:d.id,Year:d.year,State:d.state,QuestionNumber:d.questionNumber,SelectedIndex:answered?d.selected:'',CorrectIndex:d.correct,IsCorrect:correct,TimeSpentSec:Number(d.time)||0,MarkedForReview:!!d.marked});if(!correct)mist.push({WrongId:id+'-'+d.id,ResultId:id,Email:e,Subject:b.subject,QuestionId:d.id,Year:d.year,State:d.state,QuestionNumber:d.questionNumber,Question:d.question,OptionsJSON:JSON.stringify(d.options||[]),CorrectIndex:d.correct,SelectedIndex:answered?d.selected:'',MistakeType:answered?'wrong':'unattempted',DateAdded:now,RevisionDueDate:due,Revised:false,ReminderSent:false,TestUrl:b.revisionTestUrl||''})});appendMany_(sh_('Answers'),SHEETS.Answers,ans);appendMany_(sh_('WrongAnswers'),SHEETS.WrongAnswers,mist);if(sid)append_(sh_('SubmittedSessions'),SHEETS.SubmittedSessions,{ExamSessionId:sid,ResultId:id,Email:e,Subject:b.subject,SubmittedAt:now});upsertRanking_(b);const emailRes=sendResultEmail_(b,rank.rank,rank.total,unlock);return{ok:true,resultId:id,rank:rank.rank,rankOutOf:rank.total,expectedRank:expectedRank_(pct),revisionAvailableAt:unlock.toISOString(),emailStatus:emailRes.status}}
function resultResponse_(r,dup){return{ok:true,duplicate:dup,resultId:r?.ResultId||'',rank:r?.Rank||'',rankOutOf:r?.RankOutOf||'',expectedRank:expectedRank_(r?.Percentage),revisionAvailableAt:r?.RevisionAvailableAt?new Date(r.RevisionAvailableAt).toISOString():null,emailStatus:'ALREADY_SENT'}}
function expectedRank_(p){p=Number(p)||0;if(p>=65)return'1 – 10';if(p>=60)return'11 – 20';if(p>=55)return'21 – 40';if(p>=50)return'41 – 60';if(p>=45)return'61 – 100';if(p>=40)return'101 – 200';if(p>=35)return'201 – 500';if(p>=30)return'501 – 1000';return'1001+'}
function upsertRanking_(b){const s=sh_('Rankings'),v=s.getDataRange().getValues(),h=v[0],sub=h.indexOf('Subject'),em=h.indexOf('Email'),bp=h.indexOf('BestPercentage'),bs=h.indexOf('BestScore'),at=h.indexOf('Attempts'),la=h.indexOf('LastAttempt'),e=email_(b.email);for(let i=1;i<v.length;i++){if(String(v[i][sub])===String(b.subject)&&email_(v[i][em])===e){const row=v[i].slice();row[bp]=Math.max(Number(row[bp])||0,Number(b.percentage)||0);row[bs]=Number(b.score)||0;row[at]=(Number(row[at])||0)+1;row[la]=new Date();s.getRange(i+1,1,1,h.length).setValues([row]);return}}append_(s,SHEETS.Rankings,{Subject:b.subject,Email:e,Name:b.name,BestPercentage:b.percentage,BestScore:b.score,Total:b.total,Attempts:1,LastAttempt:new Date()})}
function resultHtml_(b,rank,unlock){const ready=new Date()>=new Date(unlock),rev=ready?`<a href="${esc_(b.revisionTestUrl||'')}" style="display:inline-block;padding:12px 18px;background:#111;color:#fff;text-decoration:none;border-radius:7px;margin:4px">Take Revision Test</a>`:`<p style="padding:12px;background:#f4f4f4;border-radius:7px">Revision Test unlocks on <b>${esc_(display_(unlock))}</b>.</p>`;return `<div style="font-family:Arial,sans-serif;max-width:680px;margin:auto;color:#222"><h2>ECET Test Result</h2><p>Dear <b>${esc_(b.name)}</b>,</p><table style="width:100%;border-collapse:collapse">${[['Test Subject',b.subject],['Test Start Date & Time',display_(b.startTime)],['Test End Date & Time',display_(b.endTime||new Date())],['Total Time Spent',minutes_(b.totalTime)],['Marks Obtained',b.score],['Percentage',b.percentage+'%'],['Total Questions',b.total],['Correct',b.correct],['Wrong',b.wrong],['Unattempted',b.unanswered],['Current Test Rank',rank],['ECET Equalized Rank',expectedRank_(b.percentage)]].map(x=>`<tr><td style="padding:9px;border-bottom:1px solid #eee"><b>${esc_(x[0])}</b></td><td style="padding:9px;border-bottom:1px solid #eee">${esc_(x[1])}</td></tr>`).join('')}</table><p style="margin-top:20px"><a href="${esc_(b.testUrl||'')}" style="display:inline-block;padding:12px 18px;background:#111;color:#fff;text-decoration:none;border-radius:7px;margin:4px">Retake Test</a>${rev}</p></div>`}
function minutes_(s){s=Math.round(Number(s)||0);const h=Math.floor(s/3600),m=Math.floor(s%3600/60),x=s%60;return h?`${h}h ${m}m ${x}s`:`${m}m ${x}s`}
function sendResultEmail_(b,rank,unused,unlock){const subject='ECET '+b.subject+' — Test Result',html=resultHtml_(b,rank,unlock);try{MailApp.sendEmail({to:email_(b.email),subject,htmlBody:html});return{status:'SENT'}}catch(err){append_(sh_('EmailQueue'),SHEETS.EmailQueue,{QueueId:Utilities.getUuid(),ToEmail:email_(b.email),EmailType:'result',Subject:subject,HtmlBody:html,CreatedAt:new Date(),SentAt:'',Status:'PENDING'});return{status:'QUEUED'}}}
function dashboard_(e){e=email_(e);const r=objs_(sh_('Results')).filter(x=>email_(x.Email)===e),w=objs_(sh_('WrongAnswers')).filter(x=>email_(x.Email)===e&&!bool_(x.Revised));const by={};r.forEach(x=>{by[x.Subject]??={subject:x.Subject,best:0,attempts:0};by[x.Subject].best=Math.max(by[x.Subject].best,Number(x.Percentage)||0);by[x.Subject].attempts++});return{attempts:r.length,best:r.length?Math.max(...r.map(x=>Number(x.Percentage)||0)):0,avg:r.length?Math.round(r.reduce((a,x)=>a+(Number(x.Percentage)||0),0)/r.length*10)/10:0,mistakes:w.length,subjects:Object.values(by)}}
function mistakes_(e){return objs_(sh_('WrongAnswers')).filter(x=>email_(x.Email)===email_(e)&&!bool_(x.Revised)).map(x=>({...x,options:JSON.parse(x.OptionsJSON||'[]'),revisionDueIso:x.RevisionDueDate?new Date(x.RevisionDueDate).toISOString():null,revised:bool_(x.Revised),mistakeType:String(x.MistakeType||'wrong').toLowerCase()}))}
function history_(e){return objs_(sh_('Results')).filter(x=>email_(x.Email)===email_(e)).sort((a,b)=>new Date(b.EndTime||b.Timestamp)-new Date(a.EndTime||a.Timestamp)).map(x=>({resultId:x.ResultId,timestamp:new Date(x.Timestamp).toISOString(),subject:x.Subject,subjectId:x.SubjectId,score:x.Score,total:x.Total,percentage:x.Percentage,correct:x.Correct,wrong:x.Wrong,unanswered:x.Unanswered,totalTimeSec:x.TotalTimeSec,rank:x.Rank,startTime:new Date(x.StartTime||x.Timestamp).toISOString(),endTime:new Date(x.EndTime||x.Timestamp).toISOString()}))}
function submitRevision_(b){const e=email_(b.email),s=sh_('WrongAnswers'),rows=s.getDataRange().getValues(),h=rows[0],idx=n=>h.indexOf(n),by=new Map((b.items||[]).map(x=>[String(x.wrongId),x])),hist=[];let correct=0,wrong=0,un=0;for(let i=1;i<rows.length;i++){const id=String(rows[i][idx('WrongId')]);if(!by.has(id)||email_(rows[i][idx('Email')])!==e)continue;const item=by.get(id),answered=item.selected!==null&&item.selected!==undefined&&item.selected!=='';const ok=answered&&Number(item.selected)===Number(rows[i][idx('CorrectIndex')]);if(ok){correct++;rows[i][idx('Revised')]=true;hist.push({Email:e,Subject:rows[i][idx('Subject')],QuestionId:rows[i][idx('QuestionId')],ActionDate:new Date(),Action:'revised',MistakeType:rows[i][idx('MistakeType')]})}else if(answered)wrong++;else un++;rows[i][idx('ReminderSent')]=false}if(rows.length>1)s.getRange(2,1,rows.length-1,h.length).setValues(rows.slice(1));appendMany_(sh_('RevisionHistory'),SHEETS.RevisionHistory,hist);return{ok:true,correct,wrong,unattempted:un}}
function createReminder_(b){const e=email_(b.email),d=new Date(b.nextRunAt);if(!e||!b.name||!b.message||isNaN(d)||d<=new Date())return{ok:false,error:'Please provide a valid name, message and future date/time.'};const id=Utilities.getUuid(),now=new Date();append_(sh_('Reminders'),SHEETS.Reminders,{ReminderId:id,Email:e,UserName:b.userName||b.name||'',Name:b.name,Message:b.message,RelatedTask:b.relatedTask||b.name,RelatedUrl:b.relatedUrl||'',Frequency:b.frequency||'once',NextRunAt:d,Status:'Active',Enabled:true,CreatedAt:now,UpdatedAt:now,LastSentAt:''});return{ok:true,id,nextRunAt:d.toISOString()}}
function updateReminder_(b){const s=sh_('Reminders'),v=s.getDataRange().getValues(),h=v[0],id=h.indexOf('ReminderId'),em=h.indexOf('Email');for(let i=1;i<v.length;i++)if(String(v[i][id])===String(b.id)&&email_(v[i][em])===email_(b.email)){const set=(n,val)=>v[i][h.indexOf(n)]=val;set('UserName',b.userName||v[i][h.indexOf('UserName')]||'');set('Name',b.name);set('Message',b.message);set('RelatedTask',b.relatedTask||b.name);set('RelatedUrl',b.relatedUrl||'');set('Frequency',b.frequency);set('NextRunAt',new Date(b.nextRunAt));set('RelatedUrl',b.relatedUrl||'');set('Status','Active');set('Enabled',true);set('UpdatedAt',new Date());s.getRange(i+1,1,1,h.length).setValues([v[i]]);return{ok:true}}return{ok:false,error:'Reminder not found.'}}
function toggleReminder_(b){const s=sh_('Reminders'),v=s.getDataRange().getValues(),h=v[0];for(let i=1;i<v.length;i++)if(String(v[i][h.indexOf('ReminderId')])===String(b.id)&&email_(v[i][h.indexOf('Email')])===email_(b.email)){v[i][h.indexOf('Enabled')]=!!b.enabled;v[i][h.indexOf('Status')]=b.enabled?'Active':'Paused';v[i][h.indexOf('UpdatedAt')]=new Date();s.getRange(i+1,1,1,h.length).setValues([v[i]]);return{ok:true}}return{ok:false,error:'Reminder not found.'}}
function deleteReminder_(b){const s=sh_('Reminders'),v=s.getDataRange().getValues(),h=v[0];for(let i=1;i<v.length;i++)if(String(v[i][h.indexOf('ReminderId')])===String(b.id)&&email_(v[i][h.indexOf('Email')])===email_(b.email)){s.deleteRow(i+1);return{ok:true}}return{ok:false,error:'Reminder not found.'}}
function reminders_(e){return objs_(sh_('Reminders')).filter(x=>email_(x.Email)===email_(e)).map(x=>({id:x.ReminderId,userName:x.UserName||'',name:x.Name,message:x.Message,relatedTask:x.RelatedTask,relatedUrl:x.RelatedUrl,frequency:x.Frequency,nextRunAt:x.NextRunAt?new Date(x.NextRunAt).toISOString():null,status:x.Status|| (bool_(x.Enabled)?'Active':'Paused'),enabled:bool_(x.Enabled),lastSentAt:x.LastSentAt?new Date(x.LastSentAt).toISOString():null}))}
function notifications_(e){return objs_(sh_('Notifications')).filter(x=>email_(x.Email)===email_(e)).sort((a,b)=>new Date(b.ScheduledAt)-new Date(a.ScheduledAt)).map(x=>({id:x.NotificationId,reminderId:x.ReminderId,name:x.Name,message:x.Message,relatedTask:x.RelatedTask,relatedUrl:x.RelatedUrl,scheduledAt:new Date(x.ScheduledAt).toISOString(),sentAt:x.SentAt?new Date(x.SentAt).toISOString():null,status:x.Status,error:x.Error||'',retryCount:Number(x.RetryCount)||0}))}
function sendReminder_(r,notificationId){const subject='Reminder: '+r.Name,html=`<div style="font-family:Arial,sans-serif;max-width:680px;margin:auto"><h2>Reminder</h2><p>Dear <b>${esc_(r.UserName||r.Name)}</b>,</p><p>${esc_(r.Message)}</p><p><b>Related task/test:</b> ${esc_(r.RelatedTask)}<br><b>Date/time:</b> ${esc_(display_(new Date(r.NextRunAt)))}</p>${r.RelatedUrl?`<p><a href="${esc_(r.RelatedUrl)}" style="display:inline-block;padding:12px 18px;background:#111;color:#fff;text-decoration:none;border-radius:7px">Open Task/Test</a></p>`:''}</div>`;try{MailApp.sendEmail({to:email_(r.Email),subject,htmlBody:html});const s=sh_('Notifications'),v=s.getDataRange().getValues(),h=v[0],i=v.findIndex(row=>String(row[h.indexOf('NotificationId')])===String(notificationId));if(i>0){v[i][h.indexOf('Status')]='Sent';v[i][h.indexOf('SentAt')]=new Date();s.getRange(i+1,1,1,h.length).setValues([v[i]])}return true}catch(err){const s=sh_('Notifications'),v=s.getDataRange().getValues(),h=v[0],i=v.findIndex(row=>String(row[h.indexOf('NotificationId')])===String(notificationId));if(i>0){v[i][h.indexOf('Status')]='Failed';v[i][h.indexOf('Error')]=String(err).slice(0,300);v[i][h.indexOf('RetryCount')]=(Number(v[i][h.indexOf('RetryCount')])||0)+1;s.getRange(i+1,1,1,h.length).setValues([v[i]])}return false}}
function processReminders(){ensureSheets_();const s=sh_('Reminders'),rows=objs_(s),now=new Date();rows.filter(r=>bool_(r.Enabled)&&String(r.Status)==='Active'&&new Date(r.NextRunAt)<=now).forEach(r=>{const n={NotificationId:Utilities.getUuid(),ReminderId:r.ReminderId,Email:r.Email,UserName:r.UserName||'',Name:r.Name,Message:r.Message,RelatedTask:r.RelatedTask,RelatedUrl:r.RelatedUrl,ScheduledAt:r.NextRunAt,SentAt:'',Status:'Pending',Error:'',RetryCount:0};append_(sh_('Notifications'),SHEETS.Notifications,n);const sent=sendReminder_(r,n.NotificationId);const rv=s.getDataRange().getValues(),h=rv[0],i=rv.findIndex(x=>String(x[h.indexOf('ReminderId')])===String(r.ReminderId));if(i>0){rv[i][h.indexOf('LastSentAt')]=new Date();if(String(r.Frequency)==='once'){rv[i][h.indexOf('Enabled')]=false;rv[i][h.indexOf('Status')]=sent?'Completed':'Paused'}else{rv[i][h.indexOf('NextRunAt')]=nextRun_(new Date(r.NextRunAt),r.Frequency);rv[i][h.indexOf('Status')]=sent?'Active':'Paused'}rv[i][h.indexOf('UpdatedAt')]=new Date();s.getRange(i+1,1,1,h.length).setValues([rv[i]])}})}
function nextRun_(d,f){const x=new Date(d);if(f==='hourly')x.setHours(x.getHours()+1);else if(f==='daily')x.setDate(x.getDate()+1);else if(f==='weekly')x.setDate(x.getDate()+7);else if(f==='monthly')x.setMonth(x.getMonth()+1);return x}
function retryNotification_(b){const ns=sh_('Notifications'),rows=ns.getDataRange().getValues(),h=rows[0],id=h.indexOf('NotificationId'),em=h.indexOf('Email');for(let i=1;i<rows.length;i++)if(String(rows[i][id])===String(b.id)&&email_(rows[i][em])===email_(b.email)){const r={Email:rows[i][em],UserName:rows[i][h.indexOf('UserName')],Name:rows[i][h.indexOf('Name')],Message:rows[i][h.indexOf('Message')],RelatedTask:rows[i][h.indexOf('RelatedTask')],RelatedUrl:rows[i][h.indexOf('RelatedUrl')],NextRunAt:new Date()};const nid=Utilities.getUuid();append_(ns,SHEETS.Notifications,{NotificationId:nid,ReminderId:rows[i][h.indexOf('ReminderId')],Email:r.Email,UserName:r.UserName||'',Name:r.Name,Message:r.Message,RelatedTask:r.RelatedTask,RelatedUrl:r.RelatedUrl,ScheduledAt:new Date(),SentAt:'',Status:'Pending',Error:'',RetryCount:0});const ok=sendReminder_(r,nid);return{ok}}return{ok:false,error:'Notification not found.'}}
function processEmailQueue(){const s=sh_('EmailQueue'),v=s.getDataRange().getValues(),h=v[0];for(let i=1;i<v.length;i++)if(String(v[i][h.indexOf('Status')]).startsWith('PENDING'))try{MailApp.sendEmail({to:v[i][h.indexOf('ToEmail')],subject:v[i][h.indexOf('Subject')],htmlBody:v[i][h.indexOf('HtmlBody')]});v[i][h.indexOf('SentAt')]=new Date();v[i][h.indexOf('Status')]='SENT';s.getRange(i+1,1,1,h.length).setValues([v[i]])}catch(err){v[i][h.indexOf('Status')]='FAILED: '+String(err).slice(0,200);s.getRange(i+1,1,1,h.length).setValues([v[i]])}}
function siteFromTestUrl_(url){const u=String(url||'');if(!u)return '';return u.split('?')[0]+'?revision=1'}
function sendRevisionUnlockEmails(){const s=sh_('Results'),rows=s.getDataRange().getValues(),h=rows[0],sent=h.indexOf('RevisionUnlockedEmailSent'),due=h.indexOf('RevisionAvailableAt'),sid=h.indexOf('SubjectId');for(let i=1;i<rows.length;i++){if(bool_(rows[i][sent])||!rows[i][due]||new Date(rows[i][due])>new Date())continue;const name=rows[i][h.indexOf('Name')],em=rows[i][h.indexOf('Email')],subject=rows[i][h.indexOf('Subject')],subjectId=rows[i][sid],url=siteFromTestUrl_(rows[i][h.indexOf('TestUrl')]||'');const fallback=url||((typeof SITE_URL==='string'&&SITE_URL!=='https://example.com/')?SITE_URL.split('?')[0]+'?revision=1':'');const html=`<div style="font-family:Arial,sans-serif"><p>Dear <b>${esc_(name)}</b>,</p><p>Your Revision Test for <b>${esc_(subject)}</b> is now unlocked.</p><p><a href="${esc_(fallback)}" style="display:inline-block;padding:12px 18px;background:#111;color:#fff;text-decoration:none;border-radius:7px">Take Revision Test</a></p></div>`;try{MailApp.sendEmail({to:email_(em),subject:'ECET Revision Test unlocked — '+subject,htmlBody:html});rows[i][sent]=true;s.getRange(i+1,1,1,h.length).setValues([rows[i]])}catch(e){}}}
function setup(){ensureSheets_();const triggers=ScriptApp.getProjectTriggers();const add=(fn,mins)=>{if(!triggers.some(t=>t.getHandlerFunction()===fn))ScriptApp.newTrigger(fn).timeBased().everyMinutes(mins).create()};add('processReminders',5);add('processEmailQueue',5);add('sendRevisionUnlockEmails',15);return'Backend ready. Sheets and automation triggers are configured.'}
